"""create eira schema

Revision ID: c69bcd5937f8
Revises: 20260804_0001
Create Date: 2026-08-04 11:08:01.079110
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c69bcd5937f8"
down_revision: str | None = "20260804_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "farmaco",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("unita_misura", sa.String(length=40), nullable=False),
        sa.Column("categoria", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("farmaco", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_farmaco_categoria"), ["categoria"], unique=False)
        batch_op.create_index(batch_op.f("ix_farmaco_nome"), ["nome"], unique=True)

    op.create_table(
        "reparto",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=128), nullable=False, comment="nome reparto"),
        sa.Column("descrizione", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "carello_farmaco",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("farmaco_id", sa.Integer(), nullable=False),
        sa.Column("reparto_id", sa.Integer(), nullable=False),
        sa.Column("quantita", sa.Integer(), nullable=False),
        sa.Column("soglia_minima", sa.Integer(), nullable=False),
        sa.Column("prossima_scadenza", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["farmaco_id"],
            ["farmaco.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reparto_id"],
            ["reparto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("farmaco_id", "reparto_id"),
    )
    with op.batch_alter_table("carello_farmaco", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_carello_farmaco_reparto_id"), ["reparto_id"], unique=False)

    op.create_table(
        "paziente",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=64), nullable=False),
        sa.Column("cognome", sa.String(length=64), nullable=False),
        sa.Column("eta", sa.Integer(), nullable=False),
        sa.Column("letto", sa.String(length=16), nullable=False),
        sa.Column("data_ricovero", sa.Date(), nullable=False),
        sa.Column("diagnosi_ingresso", sa.String(length=512), nullable=False),
        sa.Column("reparto_id", sa.Integer(), nullable=False),
        sa.Column("dimesso", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reparto_id"],
            ["reparto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("paziente", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_paziente_reparto_id"), ["reparto_id"], unique=False)

    op.create_table(
        "turno",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("mattina", "pomeriggio", "notte", "riposo", "ferie", "ferie_estive", name="tipoturno"),
            nullable=False,
        ),
        sa.Column("reparto_id", sa.Integer(), nullable=False),
        sa.Column("ora_inizio", sa.Time(), nullable=False),
        sa.Column("ora_fine", sa.Time(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reparto_id"],
            ["reparto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data", "tipo", "reparto_id"),
    )
    with op.batch_alter_table("turno", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_turno_reparto_id"), ["reparto_id"], unique=False)

    op.create_table(
        "utente",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("nome", sa.String(length=64), nullable=False),
        sa.Column("cognome", sa.String(length=64), nullable=False),
        sa.Column("ruolo", sa.Enum("infermiere", "caposala", name="ruoloutente"), nullable=False),
        sa.Column("reparto_id", sa.Integer(), nullable=False),
        sa.Column("stato", sa.Enum("in_attesa", "attivo", "disattivato", name="statoutente"), nullable=False),
        sa.Column("avatar_path", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["reparto_id"],
            ["reparto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("utente", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_utente_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_utente_reparto_id"), ["reparto_id"], unique=False)

    op.create_table(
        "assegnazione_turno",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("turno_id", sa.Integer(), nullable=False),
        sa.Column("infermiere_id", sa.Integer(), nullable=False),
        sa.Column("stato", sa.Enum("attiva", name="statoassegnazione"), nullable=False),
        sa.ForeignKeyConstraint(
            ["infermiere_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turno_id"],
            ["turno.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("turno_id", "infermiere_id"),
    )
    with op.batch_alter_table("assegnazione_turno", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assegnazione_turno_infermiere_id"), ["infermiere_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_assegnazione_turno_stato"), ["stato"], unique=False)

    op.create_table(
        "consegna_sbar",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paziente_id", sa.Integer(), nullable=False),
        sa.Column("turno_id", sa.Integer(), nullable=False),
        sa.Column("autore_id", sa.Integer(), nullable=False),
        sa.Column("situation", sa.Text(), nullable=False),
        sa.Column("background", sa.Text(), nullable=False),
        sa.Column("assessment", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("priorita", sa.Enum("normale", "urgente", name="prioritaconsegna"), nullable=False),
        sa.Column("creata_il", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["autore_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paziente_id"],
            ["paziente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turno_id"],
            ["turno.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paziente_id", "turno_id"),
    )
    with op.batch_alter_table("consegna_sbar", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_consegna_sbar_turno_id"), ["turno_id"], unique=False)

    op.create_table(
        "movimento_farmaco",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("carello_farmaco_id", sa.Integer(), nullable=False),
        sa.Column("autore_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("quantita_dopo", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["autore_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["carello_farmaco_id"],
            ["carello_farmaco.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movimento_farmaco", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_movimento_farmaco_carello_farmaco_id"), ["carello_farmaco_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_movimento_farmaco_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "parametri_vitali",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paziente_id", sa.Integer(), nullable=False),
        sa.Column("autore_id", sa.Integer(), nullable=False),
        sa.Column("turno_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("temperatura", sa.Float(), nullable=False),
        sa.Column("frequenza_cardiaca", sa.Integer(), nullable=False),
        sa.Column("pressione_sistolica", sa.Integer(), nullable=False),
        sa.Column("pressione_diastolica", sa.Integer(), nullable=False),
        sa.Column("frequenza_respiratoria", sa.Integer(), nullable=False),
        sa.Column("saturazione_o2", sa.Integer(), nullable=False),
        sa.Column("scala_dolore", sa.Integer(), nullable=False),
        sa.Column(
            "stato_coscienza",
            sa.Enum("vigile", "verbale", "dolore", "coma", name="statocoscienza"),
            nullable=False,
        ),
        sa.Column("ossigeno", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["autore_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paziente_id"],
            ["paziente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turno_id"],
            ["turno.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("parametri_vitali", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_parametri_vitali_paziente_id"), ["paziente_id"], unique=False)

    op.create_table(
        "password_reset_requirement",
        sa.Column("utente_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["utente_id"],
            ["utente.id"],
        ),
        sa.PrimaryKeyConstraint("utente_id"),
    )
    op.create_table(
        "profilo_infermiere",
        sa.Column("utente_id", sa.Integer(), nullable=False),
        sa.Column("ore_contrattuali_mensili", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["utente_id"],
            ["utente.id"],
        ),
        sa.PrimaryKeyConstraint("utente_id"),
    )
    op.create_table(
        "richiesta_ferie",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("infermiere_id", sa.Integer(), nullable=False),
        sa.Column("data_inizio", sa.Date(), nullable=True),
        sa.Column("data_fine", sa.Date(), nullable=True),
        sa.Column(
            "stato",
            sa.Enum("in_attesa", "approvata", "rifiutata", name="statorichiestaferie"),
            nullable=False,
        ),
        sa.Column("creata_il", sa.DateTime(), nullable=False),
        sa.Column("risposta_caposala_id", sa.Integer(), nullable=True),
        sa.Column("risposta_caposala_il", sa.DateTime(), nullable=True),
        sa.Column("motivo_rifiuto", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["infermiere_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risposta_caposala_id"],
            ["utente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("richiesta_ferie", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_richiesta_ferie_infermiere_id"), ["infermiere_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_richiesta_ferie_stato"), ["stato"], unique=False)

    op.create_table(
        "valutazione_conley",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paziente_id", sa.Integer(), nullable=False),
        sa.Column("autore_id", sa.Integer(), nullable=False),
        sa.Column("data_valutazione", sa.Date(), nullable=False),
        sa.Column("storia_cadute", sa.Integer(), nullable=False),
        sa.Column("deficit_visivo", sa.Integer(), nullable=False),
        sa.Column("alterazione_eliminazione", sa.Integer(), nullable=False),
        sa.Column("agitazione", sa.Integer(), nullable=False),
        sa.Column("deficit_vista_osservato", sa.Integer(), nullable=False),
        sa.Column("andatura_alterata", sa.Integer(), nullable=False),
        sa.Column("punteggio_totale", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["autore_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paziente_id"],
            ["paziente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valutazione_conley", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valutazione_conley_paziente_id"), ["paziente_id"], unique=False)

    op.create_table(
        "valutazione_norton",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paziente_id", sa.Integer(), nullable=False),
        sa.Column("autore_id", sa.Integer(), nullable=False),
        sa.Column("data_valutazione", sa.Date(), nullable=False),
        sa.Column("condizioni_generali", sa.Integer(), nullable=False),
        sa.Column("stato_mentale", sa.Integer(), nullable=False),
        sa.Column("attivita", sa.Integer(), nullable=False),
        sa.Column("mobilita", sa.Integer(), nullable=False),
        sa.Column("incontinenza", sa.Integer(), nullable=False),
        sa.Column("punteggio_totale", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["autore_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paziente_id"],
            ["paziente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("valutazione_norton", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_valutazione_norton_paziente_id"), ["paziente_id"], unique=False)

    op.create_table(
        "voce_diario_cedema",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paziente_id", sa.Integer(), nullable=False),
        sa.Column("autore_id", sa.Integer(), nullable=False),
        sa.Column("turno_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("coscienza", sa.Text(), nullable=False),
        sa.Column("emotivita", sa.Text(), nullable=False),
        sa.Column("dolore", sa.Text(), nullable=False),
        sa.Column("emodinamica", sa.Text(), nullable=False),
        sa.Column("mobilizzazione", sa.Text(), nullable=False),
        sa.Column("allert", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["autore_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paziente_id"],
            ["paziente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turno_id"],
            ["turno.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("voce_diario_cedema", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_voce_diario_cedema_paziente_id"), ["paziente_id"], unique=False)

    op.create_table(
        "richiesta_cambio_turno",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("assegnazione_turno_id", sa.Integer(), nullable=False),
        sa.Column("assegnazione_collega_id", sa.Integer(), nullable=True),
        sa.Column("richiedente_id", sa.Integer(), nullable=False),
        sa.Column("collega_id", sa.Integer(), nullable=False),
        sa.Column(
            "stato",
            sa.Enum(
                "in_attesa_collega",
                "rifiutata_collega",
                "in_attesa_caposala",
                "rifiutata_caposala",
                "approvata",
                name="statocambioturno",
            ),
            nullable=False,
        ),
        sa.Column("creata_il", sa.DateTime(), nullable=False),
        sa.Column("risposta_collega_il", sa.DateTime(), nullable=True),
        sa.Column("risposta_caposala_id", sa.Integer(), nullable=True),
        sa.Column("risposta_caposala_il", sa.DateTime(), nullable=True),
        sa.Column("motivo_rifiuto", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["assegnazione_collega_id"],
            ["assegnazione_turno.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assegnazione_turno_id"],
            ["assegnazione_turno.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collega_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["richiedente_id"],
            ["utente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risposta_caposala_id"],
            ["utente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("richiesta_cambio_turno", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_richiesta_cambio_turno_assegnazione_collega_id"),
            ["assegnazione_collega_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_richiesta_cambio_turno_assegnazione_turno_id"),
            ["assegnazione_turno_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_richiesta_cambio_turno_collega_id"), ["collega_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_richiesta_cambio_turno_richiedente_id"), ["richiedente_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_richiesta_cambio_turno_stato"), ["stato"], unique=False)

    op.create_table(
        "richiesta_ferie_preferenza",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("richiesta_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("data_inizio", sa.Date(), nullable=False),
        sa.Column("data_fine", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["richiesta_id"],
            ["richiesta_ferie.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("richiesta_id", "rank"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("richiesta_ferie_preferenza")
    with op.batch_alter_table("richiesta_cambio_turno", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_richiesta_cambio_turno_stato"))
        batch_op.drop_index(batch_op.f("ix_richiesta_cambio_turno_richiedente_id"))
        batch_op.drop_index(batch_op.f("ix_richiesta_cambio_turno_collega_id"))
        batch_op.drop_index(batch_op.f("ix_richiesta_cambio_turno_assegnazione_turno_id"))
        batch_op.drop_index(batch_op.f("ix_richiesta_cambio_turno_assegnazione_collega_id"))

    op.drop_table("richiesta_cambio_turno")
    with op.batch_alter_table("voce_diario_cedema", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voce_diario_cedema_paziente_id"))

    op.drop_table("voce_diario_cedema")
    with op.batch_alter_table("valutazione_norton", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valutazione_norton_paziente_id"))

    op.drop_table("valutazione_norton")
    with op.batch_alter_table("valutazione_conley", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_valutazione_conley_paziente_id"))

    op.drop_table("valutazione_conley")
    with op.batch_alter_table("richiesta_ferie", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_richiesta_ferie_stato"))
        batch_op.drop_index(batch_op.f("ix_richiesta_ferie_infermiere_id"))

    op.drop_table("richiesta_ferie")
    op.drop_table("profilo_infermiere")
    op.drop_table("password_reset_requirement")
    with op.batch_alter_table("parametri_vitali", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_parametri_vitali_paziente_id"))

    op.drop_table("parametri_vitali")
    with op.batch_alter_table("movimento_farmaco", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movimento_farmaco_timestamp"))
        batch_op.drop_index(batch_op.f("ix_movimento_farmaco_carello_farmaco_id"))

    op.drop_table("movimento_farmaco")
    with op.batch_alter_table("consegna_sbar", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consegna_sbar_turno_id"))

    op.drop_table("consegna_sbar")
    with op.batch_alter_table("assegnazione_turno", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assegnazione_turno_stato"))
        batch_op.drop_index(batch_op.f("ix_assegnazione_turno_infermiere_id"))

    op.drop_table("assegnazione_turno")
    with op.batch_alter_table("utente", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_utente_reparto_id"))
        batch_op.drop_index(batch_op.f("ix_utente_email"))

    op.drop_table("utente")
    with op.batch_alter_table("turno", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_turno_reparto_id"))

    op.drop_table("turno")
    with op.batch_alter_table("paziente", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paziente_reparto_id"))

    op.drop_table("paziente")
    with op.batch_alter_table("carello_farmaco", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_carello_farmaco_reparto_id"))

    op.drop_table("carello_farmaco")
    op.drop_table("reparto")
    with op.batch_alter_table("farmaco", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_farmaco_nome"))
        batch_op.drop_index(batch_op.f("ix_farmaco_categoria"))

    op.drop_table("farmaco")
    # ### end Alembic commands ###
